### ISSUE TITLE
Python 3: dependencies cleanup

### ISSUE THREAD

**Issue by sergirubio** [tango-controls/PANIC#15]
Migrating to python 3 and Qt5 will require to drop taurus dependency

The alternative is to go to web-based application only

**Comment by Ingvord** [comment]
+1 for the web only

**Comment by sergirubio** [comment]
There's a branch to test from S2innovation :  

https://github.com/S2Innovation/PANIC/tree/python3

**Comment by sergirubio** [comment]
the project has been moved to gitlab and the work will continue there, I'm actually reviewing all issues and it should be fixed soon

https://gitlab.com/tango-controls/panic/-/issues?sort=created_date&state=opened

if you have a gitlab user, just make a comment on your issue and I'll try to link it back to you
