### ISSUE TITLE
New panel does not show with alarm list empty

### ISSUE THREAD

**Issue by sly74fr** [tango-controls/PANIC#2]
Re,

I tried with taurus 3.7.3, 3.7.0 and 3.6.0 and still can't get the editor to show when clicking its button.
We launched python editor.py by hand to add a first alarm and then it works as expected...

Best regards,

**Comment by sergirubio** [comment]
... I'm using 3.7 and I don't have this issue, do you have any traceback in the console when it fails?

Sergi

**Comment by sly74fr** [comment]
Sadly there is no output when this occurs ☹️

**Comment by sergirubio** [comment]
Well, I reproduced the error with an empty database; I'll try to fix it.
Sergi

**Comment by sergirubio** [comment]
Panic gui assumed that devices were created first, bad assumption.

I uploaded a fix that shows a warning message from button New instead, now I'll add a button to the device config window to allow adding devices from there.

Sergi

**Comment by sergirubio** [comment]
Done in last commit, I close the issue

**Comment by sly74fr** [comment]
Thank you very much !
