### ISSUE TITLE
PANIC GUI embedded as a widget in a main window

### ISSUE THREAD

**Issue by almarass** [tango-controls/PANIC#26]
Hi,
I tried to embed PANIC GUI in another window.
The code snippet at the bottom works embedding 'xterm', but not PANIC GUI.

The configuration is as follows:
Ubuntu 16.04
Python 2.7.12
Qt version 4.8.7
PyQt version 4.11.4

Is there some way to do it?

Thanks,
Alex
-------------------------
#!/usr/bin/env python
#-*- coding:utf-8 -*-

import sys
from PyQt4.QtCore import *
from PyQt4.QtGui import *

class embeddedTerminal(QWidget):

    def __init__(self):

        QWidget.__init__(self)
        self.resize(800, 600)
        self.process  = QProcess(self)
        self.terminal = QWidget(self)
        layout = QVBoxLayout(self)
        layout.addWidget(self.terminal)

        self.process.start(
            'xterm',[
            #'python',['/home/tango-cs/Downloads/PANIC-6.5.1/panic/gui/gui.py',
            #'/home/tango-cs/src/tango-9.2.5a/lib/java/logviewer',[
            '-into', str(self.terminal.winId())]
        )

if __name__ == "__main__":
    app = QApplication(sys.argv)
    main = embeddedTerminal()
    main.show()
    sys.exit(app.exec_())

**Comment by sergirubio** [comment]
the project has been moved to gitlab and the work will continue there, I'm actually reviewing all issues and it should be fixed soon

https://gitlab.com/tango-controls/panic/-/issues?sort=created_date&state=opened

if you have a gitlab user, just make a comment on your issue and I'll try to link it back to you

**Comment by sergirubio** [comment]
apart of that, I have panic embedded in other gui's, specifically taurus gui and it works, so I will review the code and check what is going on (but, on the gitlab issue)
