### ISSUE TITLE
Connection with LDAP

### ISSUE THREAD

**Issue by gwen-soleil** [tango-controls/PANIC#29]
How do PANIC connect to LDAP directory? What modules are needed?
Can we have some documentation on how to use it and what it does?

Thanks in advance!

**Comment by sergirubio** [comment]
hi, gwen, did I already provided you the code for the widget?

the project has been moved to gitlab and the work will continue there, I'm actually reviewing all issues and it should be fixed soon

https://gitlab.com/tango-controls/panic/-/issues?sort=created_date&state=opened

if you have a gitlab user, just make a comment on your issue and I'll try to link it back to you
