### ISSUE TITLE
RAISE referenced without assignment

### ISSUE THREAD

**Issue by TNoga0** [tango-controls/PANIC#31]
As in the linked line in **EvaluateFormula:**

https://github.com/tango-controls/PANIC/blob/78bfa7808827117369ecccb12341f1b1c088ec97/panic/ds/PyAlarm.py#L1764

shouldn't RAISE be initialized somehow? In some cases code does not reach the initialization in try, so it's outputting the error of referencing without assignment.

**Comment by sergirubio** [comment]
Yes, it's True, value should be initialized at the beginning of the function.
I'll do a patch for it.

**Comment by sergirubio** [comment]
Fixed by [develop 941ef2e]
