### ISSUE TITLE
Issue when disabling alarms from the GUI, one after the other

### ISSUE THREAD

**Issue by mrosanes** [tango-controls/PANIC#32]
During summer shutdown powercut at Mistral, I wanted to disable all alarms before turning down ibl0901. 
If disabling the alarms from panic GUI, one after the other at a relative fast pace, some alarms are not correctly deactivated. They show the checkbox cross as if they were deactivated, but they remain in status active with the green color. In order to solve this problem, I have retried to activate and deactivate them again using the checkbox and waiting until each of them was inactive, before passing to deactivate the next one.

**Comment by mrosanes** [comment]
On 03/09/2019 observed again the same problem, of refresh of the status of the alarms in the GUI (green/grey color for active/inactive alarms is not always correctly attributed in the panic GUI)

This has been observed when trying to deactivate four alarms after a bakeout (communications, high temperature, low temperature and bakeout pressure alarm): only 2 alarms where deactivated correctly showing the grey color.

After that, I tried to restart de DS of PyAlarm to see if this could solve the problem, but I observed that the persistence of the alarm status was not kept: some of the disabled alarms where reenabled after restarting the DS.

**Comment by sergirubio** [comment]
Which are the versions that you have installed? Can you check it?

Sergi

**Comment by mrosanes** [comment]
In pcbl0903 and pcbl0905 the installed packages are the blisspackage 7.3 of Panic-AlarmsGUI

you can check these alarms in panic from pcbl0905:
- mistral_bakeout_low_temp is correctly deactivated (grey color)
- mistral_bakeout_M4_comms is correctly deactivated (grey color)
- mistral_bakeout_high_temp is incorrectly deactivated (the alarm is inactive but it remains in green in panicGUI)
- mistral_bakeout_pressure_m4 is incorrectly deactivated (the alarm is inactive but it remains in green in panicGUI)

**Comment by sergirubio** [comment]
solved in latest panic sources
