### ISSUE TITLE
SHELVD state is displayed as NORM in python

### ISSUE THREAD

**Issue by gandorm** [tango-controls/PANIC#42]
Hi,

Alarms states seem to be different in panic GUI and using python.

Steps to reproduce:

- create an alarm in panic GUI, which will remind in NORM state
- disable an alarm
- alarm changes state to SHELVD
- in python console type:
```
from panic import alarmapi
alarms = alarmapi.api()
my_alarm = alarms['alarm_name']
my_alarm.get_state()
```

**Expected:**
Show SHELVD state
**Actual:**
Showing NORM state

Any ideas what can be wrong?

**Comment by sergirubio** [comment]
hi, the project has been moved to gitlab and the work will continue there, I'm actually reviewing all issues and it should be fixed soon

https://gitlab.com/tango-controls/panic/-/issues?sort=created_date&state=opened

if you have a gitlab user, just make a comment on your issue and I'll try to link it back to you
